### ISSUE TITLE
How deploy notebook in Ubuntu 20

### ISSUE THREAD

**Issue by johnfelipe** [mattborghi/mnist-webapp#8]
I'm new in your app, pls tell me how can deploy all exactly like your demo page
Tnks

**Comment by mattborghi** [comment]
Hi, I have just updated the [README](https://github.com/mattborghi/mnist-webapp#frontend-development) file with clearer instructions.

Feel free to ask me again if you keep having issues or to ask about a particular step.

If your question is more related to how to deploy something like this to GitHub Pages just let me know and I will tell you.
